<font color="#CA3532"><h1 align="left">Inteligencia Artificial Aplicada a la Bolsa (MIAX-11)</h1></font>
<font color="#5b5a59"><h2 align="left">Introducción a las redes neuronales artificiales</h2></font>
<font color="#5b5a59"><h3 align="left">Noviembre 2023</h3></font>

### <font color="#CA3532">Docentes</font>

#### Luis Fernando Lago Fernández

Universidad Autónoma de Madrid

luis.lago@uam.es

#### Christian Oliva Moya

Universidad Autónoma de Madrid

christian.oliva@uam.es

### <font color="#CA3532">Material del curso</font>

Todo el material que utilicemos en estas clases lo puedes descargar de GITHUB:

- ### https://github.com/christianolivamoya/MIAX11-ANN

### <font color="#CA3532">Presentación del curso</font>

Enlace a las [transparencias de presentación](https://luisferuam.github.io/MIAX-11/course_presentation/course_presentation.html)

### <font color="#CA3532">Recursos</font>

- *Neural Networks and Deep Learning*, M. Nielsen, online
book, http://neuralnetworksanddeeplearning.com

- *Deep Learning*, I. Goodfellow, Y. Bengio, A. Courville, MIT
Press, http://www.deeplearningbook.org/

- *Convolutional Neural Networks for Visual Recognition*,
curso Stanford, http://cs231n.stanford.edu/

- *Introduction to Deep Learning*, curso MIT, http://introtodeeplearning.com/

- Tutoriales de TensorFlow,
https://www.tensorflow.org/tutorials/

- TensorFlow Playground,
http://playground.tensorflow.org

### <font color="#CA3532">Entorno de trabajo</font>

Todo el código del curso estará desarrollado con *Google Colab*, un entorno de trabajo basado en el *Jupyter Notebook* (https://jupyter.org/) que no necesita configuración y funciona en la nube:
- https://colab.research.google.com/notebooks/welcome.ipynb?hl=es-419
- https://www.youtube.com/watch?v=inN8seMm7UI

Necesitarás una cuenta de Google. Si quieres trabajar en local tendrás que instalar *python 3* (recomiendo la distribución *Anaconda*, https://www.anaconda.com/), y *TensorFlow* (https://www.tensorflow.org/).

Esta es la versión de python que utiliza *Colab*:

In [ ]:
!python --version

### <font color="#CA3532">Crea tu propio directorio en Drive</font>

Para poder trabajar con el material proporcionado, descarga los Notebooks de Github. El material de clase se puede ir actualizando a lo largo del curso. Puedes seguir los siguientes pasos:

1. Entra en tu Google Drive.
2. Crea un directorio local en tu Google Drive, por ejemplo, ``MI_CARPETA_MIAX11``.
3. Sube los Notebooks descargados a tu directorio local.
4. Ahora sí, tendrás permiso de escritura en los Notebooks para poder editarlos y trabajar con ellos.

### <font color="#CA3532">Requisitos previos</font>

**Álgebra lineal:**

- Escalares, vectores, matrices, tensores.
- Transposición.
- Producto de matrices (dot product).

Ver capítulo 2 del libro de Goodfellow: https://www.deeplearningbook.org/contents/linear_algebra.html

Ver apuntes *Linear Algebra Review and Reference, Zico Kolter, 2015*, http://cs229.stanford.edu/section/cs229-linalg.pdf

**Programación con python y NumPy:**

- NumPy arrays.
- Indexación de arrays.
- Matemática con arrays.
- Broadcasting.

Ver tutorial en el curso de Stanford: https://cs231n.github.io/python-numpy-tutorial/#numpy

### <font color="#CA3532">Ejercicios</font>

Para ver cómo lleváis los conceptos básicos de álgebra lineal.

Sean los siguientes vectores y matrices:

$$
{\bf x} = (3, -2, 4)^{t},\;\;\;
{\bf y} = (1, 5, 2)^{t},\;\;\;
{\bf A} =
\begin{pmatrix}
1 & 2 & 3\\
-3 & 1 & 2
\end{pmatrix},\;\;\;
{\bf z} = (-1, 2)^{t}
$$

Calcula:

1. ${\bf x}^{t} {\bf y}$

2. ${\bf A} {\bf x}$

3. ${\bf A}^{t}$

4. ${\bf z}^{t} {\bf A}$

### <font color="#CA3532">Ejercicios</font>

Para evaluar vuestro nivel de python y NumPy.

In [ ]:
import numpy as np

In [ ]:
# (1) Crea una matriz (array) de numpy de dimension 4x3, con numeros aleatorios segun gausiana:
pass

In [ ]:
# (2) Crea una matriz (array) de numpy de dimension 3x2, con numeros aleatorios segun gausiana:
pass

In [ ]:
# (3) Multiplica las dos matrices (producto matricial):
pass

In [ ]:
# (4) Suma la segunda matriz a las primeras 3x2 posiciones de la primera matriz:
pass

In [ ]:
# (5) Crea la siguiente tabla de multiplicar sin usar bucles:
# [[  1   2   3   4   5   6   7   8   9  10]
#  [  2   4   6   8  10  12  14  16  18  20]
#  [  3   6   9  12  15  18  21  24  27  30]
#  [  4   8  12  16  20  24  28  32  36  40]
#  [  5  10  15  20  25  30  35  40  45  50]
#  [  6  12  18  24  30  36  42  48  54  60]
#  [  7  14  21  28  35  42  49  56  63  70]
#  [  8  16  24  32  40  48  56  64  72  80]
#  [  9  18  27  36  45  54  63  72  81  90]
#  [ 10  20  30  40  50  60  70  80  90 100]]
pass

In [ ]:
# (6) Sin usar bucles, transforma la variable t a codificación one-hot y compara
# el resultado con el obtenido con keras.utils.to_categorical
from tensorflow.keras.utils import to_categorical

t = np.random.randint(0, 4, 10)
print(t)

one_hot_t = to_categorical(t)
print(one_hot_t)

# To do...


In [ ]:
# (7) Sin usar bucles, calcula la matriz de distancias entre todos los
# vectores (2D) contenidos en el array p. Compara el resultado con el
# obtenido con scipy.spatial.distance.pdist
# Nota: ||x-y||^2 = ||x||^2 + ||y||^2 - 2xy
from scipy.spatial.distance import pdist, squareform
p = np.random.randint(-5, 5, (6, 2))
print(p)

d = squareform(pdist(p))
print(d)

# To do...

### <font color="#CA3532">Regresión lineal y descenso por gradiente</font>

Ver estas [notas](https://luisferuam.github.io/DLFBT/linear_regression/linear_regression.html).

### <font color="#CA3532">Regresión logística</font>

Ver estas [notas](https://luisferuam.github.io/DLFBT/logistic_regression/logistic_regression.html).

### <font color="#CA3532">Modelos no lineales</font>

Ver estas [notas](https://luisferuam.github.io/DLFBT/non_linear_models/non_linear_models.html).